version: '3.8'

services:
  # Laravel App
  app:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: task_management_be
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  # Vue Frontend
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: task_management_fe
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    working_dir: /app

volumes:
  mysql_data:
