version: '3.8'

services:
  # Laravel App
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_management_be
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: task_manager
      DB_USERNAME: root
      DB_PASSWORD: root
    command: php artisan serve --host=0.0.0.0 --port=8000

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  # Vue Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task_management_fe
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    working_dir: /app

volumes:
  mysql_data:
